kind: Pod
apiVersion: v1
metadata:
  name: test-redis
  namespace: production
  labels:
    app: test-redis
spec:
  containers:
    - name: test-redis
      image: 'letanthang/testredis'
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      env:
        - name: REDIS_HOST
          # value: 'my-redis-master.redis:6379'
          value: '10.46.47.43:6379'
          # value: '10.194.110.227:6379'
      resources:
        limits:
          cpu: 320m
        requests:
          cpu: 200m
      

      
